# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Type', (('mtn', 'Mountain'), ('rd', 'Road'), ('cruse', 'Cruiser'))), ('Frame', (('fs', 'Full Suspension'), ('ht', 'Hardtail'))), ('unknown', 'Unknown')], max_length=10)),
                ('build', models.CharField(max_length=100)),
            ],
        ),
    ]
