# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_bikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybike',
            name='frame_type',
            field=models.CharField(choices=[('fs', 'Full Suspension'), ('ht', 'Hardtail')], default='fs', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mybike',
            name='year',
            field=models.IntegerField(default=2014),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mybike',
            name='type',
            field=models.CharField(choices=[('mtn', 'Mountain'), ('rd', 'Road'), ('cruse', 'Cruiser')], max_length=10),
        ),
    ]
