# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_bikes', '0002_auto_20160613_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybike',
            name='picture',
            field=models.ImageField(default=False, upload_to='/static/images/'),
        ),
    ]
